import type { Metadata } from "next";
import { Montserrat, PT_Sans } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "700"], // choose weights you need
});

const ptsans = PT_Sans({
  subsets: ["latin"],
  variable: "--font-ptsans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Katipunan Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${ptsans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
