import type { Metadata } from "next";
import { Montserrat, PT_Sans } from "next/font/google";
import "./globals.css";

// --- 1. Import the new components ---
// --- Make sure these paths are correct for your project! ---
import { PostModalProvider } from "@/app/component/General/Announcement/Posts/Comment/postModalContext";
import PostModal from "./component/General/Announcement/Posts/Comment/PostModal";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "700"],
});

const ptsans = PT_Sans({
  subsets: ["latin"],
  variable: "--font-ptsans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Katipunan Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${ptsans.variable} antialiased`}>
        {/* --- 2. Wrap your children with the provider --- */}
        <PostModalProvider>
          {children}

          {/* --- 3. Render the Modal component (it's hidden by default) --- */}
          <PostModal />
        </PostModalProvider>
      </body>
    </html>
  );
}
